### ISSUE TITLE
My Models: Info button shows as selected even after closing its modal.

### ISSUE THREAD

**Issue by joulei** [moxin-org/moxin#131]
After closing the information modal, the icon button should not be grayed out anymore.

https://github.com/moxin-org/moxin/assets/22042418/78ed9157-06ad-46d0-b299-22e25c44493d

**Comment by ZhangHanDong** [comment]
[PR #180 ](https://github.com/moxin-org/moxin/pull/180)

**Comment by joulei** [comment]
This also happens for other modals, the underlying issue has to do with updating focus when overlays take over the screen.
We'll solve this within Makepad, so it shouldn't require changes in Moxin for now.

See comments for more information:
https://github.com/moxin-org/moxin/pull/180#issuecomment-2255389164
https://github.com/moxin-org/moxin/pull/180#issuecomment-2255584483

**Comment by jmbejar** [comment]
This issues should be fixed on main now.
