### ISSUE TITLE
Chat Panel: missing tick for currently selected model in the models dropdown.

### ISSUE THREAD

**Issue by joulei** [moxin-org/moxin#132]
Currently when navigating the models dropdown in the chat screen, there's no indication of which is the currently selected model.

<img width="685" alt="Screenshot 2024-07-01 at 9 56 01 AM" src="https://github.com/moxin-org/moxin/assets/22042418/8b055b53-1f85-4237-9334-8a96d77aed46">

The model selected model (the one showing on the dropdown while it's closed) should be ticked as follows: 
<img width="461" alt="Screenshot 2024-07-01 at 9 59 23 AM" src="https://github.com/moxin-org/moxin/assets/22042418/099c5075-ee96-487f-81c3-86bb3396d098">

**Comment by jmbejar** [comment]
This is now implemented in `dev`, so we close the issue 👏
