### ISSUE TITLE
Crash error: logger with name 'wasi_logging_stdout' already exists

### ISSUE THREAD

**Issue by jmbejar** [moxin-org/moxin#158]
The application crashes when a second model is loaded, showing the following error:

```
libc++abi: terminating due to uncaught exception of type spdlog::spdlog_ex: logger with name 'wasi_logging_stdout' already exists
```

It happens in the following flows:
- Choosing a new model in the main dropdown in the Chat screen
- Using the "Start Chat" buttons in My Models view
- Switching to another conversation (in Chat screen) where a different model was the last one used.

In all cases, the backend seems to struggle to load a new model.

**Comment by L-jasmine** [comment]
@hydai https://github.com/moxin-org/moxin/blob/fb3d19c0307ff11d71f55f99665d13e728f34614/moxin-backend/src/backend_impls/api_server.rs#L100-L107

**Comment by L-jasmine** [comment]
@jmbejar  Try this simple way to fix the problem , delete the WasiNNLogging plugin from your plugins folder

**Comment by jmbejar** [comment]
@L-jasmine After removing `~/.wasmedge/plugin/libwasmedgePluginWasiLogging.dylib` the issue didn't happen again, so the solution to this issue is related with this plugin. What should be done to avoid this issue in other users?

**Comment by guofoo** [comment]
Can we provide a version check to make sure the FE and BE stays consistent - and give a message to user when things are out of alignment and need further steps (such as re-installing something)
