### ISSUE TITLE
Chat with stream option off is not longer working

### ISSUE THREAD

**Issue by jmbejar** [moxin-org/moxin#161]
After the recent big changes in the backend, I'm getting this error when the stream option is off.

```
[2024-07-22T13:55:32Z INFO  chat_completions] Finish chat completions in non-stream mode
[2024-07-22T13:55:32Z INFO  chat_completions_handler] Send the chat completion response.
[2024-07-22T13:55:32Z INFO  response] version: HTTP/1.1, body_size: 924, status: 200, is_informational: false, is_success: true, is_redirection: false, is_client_error: false, is_server_error: false
Error receiving response chunk: error decoding response body: missing field `system_fingerprint` at line 1 column 924

Caused by:
    missing field `system_fingerprint` at line 1 column 924
```

**Comment by jmbejar** [comment]
@L-jasmine I checked the frontend and the communication layer with the backend code, but I haven't found any related issue. Looks related with the new backend architecture, where the `system_fingerprint` is missed from the origin.

**Comment by L-jasmine** [comment]
@jmbejar  How to trigger it?
https://github.com/moxin-org/moxin/blob/5ec46d71e100dc4494cd73c2fce4ce5fb8303503/moxin-backend/src/backend_impls/api_server.rs#L247-L249
I think the bug is likely here, but is there a way to trigger it?

**Comment by jmbejar** [comment]
> @jmbejar How to trigger it?
> 
> https://github.com/moxin-org/moxin/blob/5ec46d71e100dc4494cd73c2fce4ce5fb8303503/moxin-backend/src/backend_impls/api_server.rs#L247-L249
> 
> 
> I think the bug is likely here, but is there a way to trigger it?

I can easily reproduce it turning off the Stream option before sending a new question to any model.

<img width="617" alt="image" src="https://github.com/user-attachments/assets/940c08d9-60b1-4de6-b622-cda4210edbe6">

**Comment by jmbejar** [comment]
@L-jasmine have you been able to reproduce the issue?

**Comment by L-jasmine** [comment]
> @L-jasmine have you been able to reproduce the issue?

yes, I will fix it tomorrow

**Comment by jmbejar** [comment]
Solution is merged to main.
