### ISSUE TITLE
Use a default system prompt when users don't provide one.

### ISSUE THREAD

**Issue by jmbejar** [moxin-org/moxin#186]
In the Chat section there is a text input where users can specify a system prompt. This is an special message to the models that goes in the beginning of the conversation and it defines how the model responds.

<img width="498" alt="image" src="https://github.com/user-attachments/assets/02254ecc-3269-45cd-b029-74a5baefc786">

However, sending an empty message is problematic. Models returns better results when using any valid system prompt, so we need to provide one if the user is leaving this field empty.

The task is to [send the following system prompt to the backend](https://github.com/moxin-org/moxin/blob/main/src/data/chats/chat.rs#L224C21-L233) when the provided one is empty:
`You are a helpful, respectful, and honest assistant.`

**Comment by joulei** [comment]
Closed by #212
