### ISSUE TITLE
After clicking on "Chat with Model", set keyboard focus to the Chat panel's `prompt` text input 

### ISSUE THREAD

**Issue by kevinaboos** [moxin-org/moxin#203]
This is a simple but convenient enhancement to improve the user experience.

## Current behavior
When clicking "Chat with Model" (or "Resume Chat") from the "My Models" screen, it takes you to the "Chat" panel and shows a new or existing conversation with the given Model. However, you then must move the mouse down to the text input box and click on it before you can start typing a message.

## Desired behavior
Instead of having to move the mouse to the text input box and click on it, that text input box should just be automatically focused on after the "Chat" panel is shown, such that you can start typing immediately without having to manually select it.

I think this is consistent with most other UIs that welcome text input -- you can just start typing without having to additionally select a specific text input.

**Comment by joulei** [comment]
Fixed by #233 and #236
