### ISSUE TITLE
WasmEdge CUDA detection not working correctly

### ISSUE THREAD

**Issue by kevinaboos** [moxin-org/moxin#225]
Line 36 of the WasmEdge [`install_v2.sh` script](https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install_v2.sh) attempts to discover the CUDA installation using `nvcc --version`, but it is hardcoded to look for `nvcc` in `/usr/local/cuda/bin/`.

On some machines, cuda is found in `/opt/...`, so this will fail.

@juntao Line 36 of the install script should use `nvcc` from the current path first, and then fall back to `/usr/local/cuda/bin/nvcc`, and then fall back to `/opt/cuda/bin/nvcc`, and finally consider cuda as non-existent.

`moxin-runner` already does this check locally in Rust code, so a short-term fix would be to directly pass in the cuda version into the invocation of `install_v2.sh`, i.e., `-c 11` or `-c 12`.

**Comment by kevinaboos** [comment]
Another potentially related issue is that CUDA doesn't actually get used even when WasmEdge successfully detects the CUDA installation.

Here are some examples of warnings/errors I observe on my Linux and Windows machines that have CUDA 12.5, but with an older Nvidia GeForce 1070Ti graphics card:

```
[warning] [WASI-NN] llama.cpp: ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
```
```
[error] [WASI-NN] llama.cpp: ggml_cuda_init: failed to initialize CUDA: CUDA driver version is insufficient for CUDA runtime version
```
```
[warning] [WASI-NN] llama.cpp: ggml_cuda_host_malloc: failed to allocate 384.00 MiB of pinned memory: CUDA driver version is insufficient for CUDA runtime version
```

**Comment by kevinaboos** [comment]
> `moxin-runner` already does this check locally in Rust code, so a short-term fix would be to directly pass in the cuda version into the invocation of `install_v2.sh`, i.e., `-c 11` or `-c 12`.

this was implemented in #226

**Comment by L-jasmine** [comment]
@hydai

**Comment by kevinaboos** [comment]
Closed by https://github.com/WasmEdge/WasmEdge/pull/3682

thanks for the fix @hydai and @L-jasmine. much appreciated!
