### ISSUE TITLE
Add a X button to clear the text input field in the model search screen

### ISSUE THREAD

**Issue by guofoo** [moxin-org/moxin#237]
![image](https://github.com/user-attachments/assets/39664a01-88d3-4dc7-87c7-1ed53ff1aef5)

Should be a X to clear the input field. Currently only way to get back to the main discover page is to manually deleting all characters in the input field.

**Comment by Guocork** [comment]
#251

**Comment by joulei** [comment]
Fixed by https://github.com/moxin-org/moxin/pull/251
