### ISSUE TITLE
Remove duplicated button in chat input field

### ISSUE THREAD

**Issue by jmbejar** [moxin-org/moxin#248]
When the app is just installed, the chat interface has an specific empty state. In this case, the chat input field should display only the disabled send button (the icon with an arrow).

Currently, it is also showing a disabled stop button, which should not be visible at this point.

![image](https://github.com/user-attachments/assets/fe9cd076-7e72-4903-92ca-e65601d69eb4)

**Comment by Guocork** [comment]
I fix this in #249
